name = "quartier"
pages_build_output_dir = "dist"
compatibility_date = "2024-12-01"

# Production environment
[env.production]
vars = { ENVIRONMENT = "production" }

# Preview environment
[env.preview]
vars = { ENVIRONMENT = "preview" }
